# ML2

# https://github.com/codebasics/py/tree/master/ML
# https://www.youtube.com/watch?v=J_LnPL3Qg70

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [29]:
df=pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [30]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [31]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [32]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [33]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [34]:
reg.intercept_

221323.00186540408

In [35]:
reg.predict([[3500,2,6],[3500,2,16]])

array([640929.00136696, 608611.82228063])

In [50]:
df1=pd.read_csv('hiring.csv')

In [51]:
df1.experience=df1.experience.fillna('zero')
df1

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [52]:
from word2number import w2n
import math
#df1.experience=df1.experience.apply(w2n.word_to_num)
test_score_median=math.floor(df1.test_score.median())
df1.experience=df1.experience.apply(w2n.word_to_num)
df1.test_score=df1.test_score.fillna(test_score_median)

In [53]:
df1

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [56]:
reg1=linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score','interview_score']],df1.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [57]:
#salary=m1*experience+m2*test_score+m3*interview_score+intercept
print('coeficient = ',reg1.coef_)
print('intercept = ',reg1.intercept_)

coeficient =  [2812.95487627 1845.70596798 2205.24017467]
intercept =  17737.26346433771


In [61]:
reg1.predict([[2,13,9]])

array([67204.51237263])

In [70]:
df1.salary=df1.salary.apply(float)

In [71]:
df1

experience  test_score  interview_score   salary
0           0         8.0                9  50000.0
1           0         8.0                6  45000.0
2           5         6.0                7  60000.0
3           2        10.0               10  65000.0
4           7         9.0                6  70000.0
5           3         7.0               10  62000.0
6          10         8.0                7  72000.0
7          11         7.0                8  80000.0